Common Provider Documentation
internetofwater/docs.geoconnex.us pull request #20
Opened 2024-07-25 20:11 UTC by C-Loftus

- Refactors the contribution docs to make it clearer for new users
- Adds info for socrata, ESRI, and CKAN
- Made a clear delineation between the example which is used as a reference and the internetofwater/pygeoapi fork which is the one that they should be applying their config to
    - I want to make the docs have a clear separation between tutorials which have an explicit goal and examples which are used for reference  
    - Previous docs had them setting up pygeoapi using the docker-compose file in the examples repo. I think we want them using the upstream pygeoapi image directly unless we turn the https://github.com/cgs-earth/pygeoapi-geoconnex-examples repo into a temlate repo (this sounds like more maintenance work, so probably not worth it)

2024-07-30 14:47 UTC, C-Loftus commented
@webb-ben would you mind checking that the docs here is correct: https://deploy-preview-20--docs-geoconnex-us.netlify.app/contributing/step-2/pygeoapi/providers/ I have not used the SODA API previously with pygeoapi, among others, and just want to be totally sure that I am not misrepresenting which providers are present in pygeoapi vs our fork.

For the ESRI and Socrata providers I brought over the info from the pygeoapi docs. For the CKAN provider I brought over the info from the pygeoapi-plugins repo.

2024-07-30 20:10 UTC, webb-ben requested changes
Looks good. Small suggestions then I think all good

2024-07-31 15:13 UTC, C-Loftus commented on docs/contributing/overview.md
>  Otherwise, if you do not currently have a platform that publishes web content about individual [features](https://docs.geoconnex.us/principles/hydrofeatures.html), or you do not have the resources or
Weirdly I had previously fixed this but this doesn't show up as outdated. Resolving this since it is no longer in this branch.

2024-07-31 15:49 UTC, C-Loftus commented on docs/contributing/step-2/pygeoapi/deployment.md
> +pygeoapi is most easily deployed with [Docker](https://www.docker.com/).
I updated this to note that users can still install from source but it is not recommended. To my understanding, `pip` `conda` `pkg` and the other formats listed on the documentation for the upstream repository would not be valid for our fork correct?

2024-07-31 15:49 UTC, webb-ben commented on docs/contributing/step-2/pygeoapi/deployment.md
> +pygeoapi is most easily deployed with [Docker](https://www.docker.com/).
Yes

2024-07-31 16:03 UTC, C-Loftus commented
Believe this should be all set now. @ksonda, this should be ready for your review at your convenience. 

Thank you for the comments Ben. I believe I have resolved all. In the future I will batch resolve in the UI for cleaner commit history in the PR. Wasn't aware that was a feature. Also for some reason the PR says 1 change requested still but I believe everything is resolved.

2024-07-31 16:29 UTC, webb-ben approved these changes

2024-07-31 16:34 UTC, ksonda approved these changes

2024-07-31 16:34 UTC, merged